name: Build Multi-Platform Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyserial bflb_mcu_tool

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      - name: List dist folder contents
        run: ls -l dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: M0SS-101-${{ matrix.os }}
          path: dist/
